# -*- coding: utf-8 -*-
from planeta_brasil.api_copa.models import Stadium, Team, Match
from datetime import datetime


def run():

    matches = [
        {
            "home": Team.objects.get(name_pt__icontains="Brasil"),
            "visited": Team.objects.get(name_pt__icontains="Croácia"),
            "day": datetime.strptime("12/06/2014 17:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena de São Paulo"),
            "type": 1,
            "group": "a",
        },
        {
            "home": Team.objects.get(name_pt__icontains="México"),
            "visited": Team.objects.get(name_pt__icontains="Camarões"),
            "day": datetime.strptime("13/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena das Dunas"),
            "type": 1,
            "group": "a",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Brasil"),
            "visited": Team.objects.get(name_pt__icontains="México"),
            "day": datetime.strptime("17/06/2014 16:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Castelão"),
            "type": 1,
            "group": "a",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Croácia"),
            "visited": Team.objects.get(name_pt__icontains="Camarões"),
            "day": datetime.strptime("18/06/2014 18:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Amazônia"),
            "type": 1,
            "group": "a",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Croácia"),
            "visited": Team.objects.get(name_pt__icontains="México"),
            "day": datetime.strptime("23/06/2014 17:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Pernambuco"),
            "type": 1,
            "group": "a",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Brasil"),
            "visited": Team.objects.get(name_pt__icontains="Camarões"),
            "day": datetime.strptime("23/06/2014 17:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Nacional de Brasília"),
            "type": 1,
            "group": "a",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Espanha"),
            "visited": Team.objects.get(name_pt__icontains="Holanda"),
            "day": datetime.strptime("13/06/2014 16:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Fonte Nova"),
            "type": 1,
            "group": "b",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Chile"),
            "visited": Team.objects.get(name_pt__icontains="Austrália"),
            "day": datetime.strptime("13/06/2014 18:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Pantanal"),
            "type": 1,
            "group": "b",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Holanda"),
            "visited": Team.objects.get(name_pt__icontains="Austrália"),
            "day": datetime.strptime("18/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Beira Rio"),
            "type": 1,
            "group": "b",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Espanha"),
            "visited": Team.objects.get(name_pt__icontains="Chile"),
            "day": datetime.strptime("18/06/2014 16:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Maracanã"),
            "type": 1,
            "group": "b",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Holanda"),
            "visited": Team.objects.get(name_pt__icontains="Chile"),
            "day": datetime.strptime("23/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena de São Paulo"),
            "type": 1,
            "group": "b",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Espanha"),
            "visited": Team.objects.get(name_pt__icontains="Austrália"),
            "day": datetime.strptime("23/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena da Baixada"),
            "type": 1,
            "group": "b",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Colômbia"),
            "visited": Team.objects.get(name_pt__icontains="Grécia"),
            "day": datetime.strptime("14/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Mineirão"),
            "type": 1,
            "group": "c",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Costa do Marfim"),
            "visited": Team.objects.get(name_pt__icontains="Japão"),
            "day": datetime.strptime("14/06/2014 22:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Pernambuco"),
            "type": 1,
            "group": "c",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Colômbia"),
            "visited": Team.objects.get(name_pt__icontains="Costa do Marfim"),
            "day": datetime.strptime("19/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Nacional de Brasília"),
            "type": 1,
            "group": "c",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Grécia"),
            "visited": Team.objects.get(name_pt__icontains="Japão"),
            "day": datetime.strptime("19/06/2014 19:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena das Dunas"),
            "type": 1,
            "group": "c",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Grécia"),
            "visited": Team.objects.get(name_pt__icontains="Costa do Marfim"),
            "day": datetime.strptime("24/06/2014 17:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Castelão"),
            "type": 1,
            "group": "c",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Colômbia"),
            "visited": Team.objects.get(name_pt__icontains="Japão"),
            "day": datetime.strptime("24/06/2014 18:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Pantanal"),
            "type": 1,
            "group": "c",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Uruguai"),
            "visited": Team.objects.get(name_pt__icontains="Costa Rica"),
            "day": datetime.strptime("14/06/2014 16:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Castelão"),
            "type": 1,
            "group": "d",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Inglaterra"),
            "visited": Team.objects.get(name_pt__icontains="Itália"),
            "day": datetime.strptime("14/06/2014 18:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Amazônia"),
            "type": 1,
            "group": "d",
        },

        {
            "home": Team.objects.get(name_pt__icontains="Uruguai"),
            "visited": Team.objects.get(name_pt__icontains="Inglaterra"),
            "day": datetime.strptime("19/06/2014 16:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena de São Paulo"),
            "type": 1,
            "group": "d",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Costa Rica"),
            "visited": Team.objects.get(name_pt__icontains="Itália"),
            "day": datetime.strptime("20/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Pernambuco"),
            "type": 1,
            "group": "d",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Uruguai"),
            "visited": Team.objects.get(name_pt__icontains="Itália"),
            "day": datetime.strptime("24/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena das Dunas"),
            "type": 1,
            "group": "d",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Costa Rica"),
            "visited": Team.objects.get(name_pt__icontains="Inglaterra"),
            "day": datetime.strptime("24/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Mineirão"),
            "type": 1,
            "group": "d",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Suíça"),
            "visited": Team.objects.get(name_pt__icontains="Equador"),
            "day": datetime.strptime("15/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Nacional de Brasília"),
            "type": 1,
            "group": "e",
        },
        {
            "home": Team.objects.get(name_pt__icontains="França"),
            "visited": Team.objects.get(name_pt__icontains="Honduras"),
            "day": datetime.strptime("15/06/2014 16:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Beira Rio"),
            "type": 1,
            "group": "e",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Suíça"),
            "visited": Team.objects.get(name_pt__icontains="França"),
            "day": datetime.strptime("20/06/2014 16:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Fonte Nova"),
            "type": 1,
            "group": "e",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Equador"),
            "visited": Team.objects.get(name_pt__icontains="Honduras"),
            "day": datetime.strptime("20/06/2014 19:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena da Baixada"),
            "type": 1,
            "group": "e",
        },

        {
            "home": Team.objects.get(name_pt__icontains="Suíça"),
            "visited": Team.objects.get(name_pt__icontains="Honduras"),
            "day": datetime.strptime("25/06/2014 16:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Amazônia"),
            "type": 1,
            "group": "e",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Equador"),
            "visited": Team.objects.get(name_pt__icontains="França"),
            "day": datetime.strptime("25/06/2014 17:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Maracanã"),
            "type": 1,
            "group": "e",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Argentina"),
            "visited": Team.objects.get(name_pt__icontains="Bósnia"),
            "day": datetime.strptime("15/06/2014 19:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Maracanã"),
            "type": 1,
            "group": "f",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Irã"),
            "visited": Team.objects.get(name_pt__icontains="Nigéria"),
            "day": datetime.strptime("16/06/2014 16:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena da Baixada"),
            "type": 1,
            "group": "f",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Bósnia"),
            "visited": Team.objects.get(name_pt__icontains="Nigéria"),
            "day": datetime.strptime("21/06/2014 18:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Pantanal"),
            "type": 1,
            "group": "f",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Argentina"),
            "visited": Team.objects.get(name_pt__icontains="Irã"),
            "day": datetime.strptime("21/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Mineirão"),
            "type": 1,
            "group": "f",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Argentina"),
            "visited": Team.objects.get(name_pt__icontains="Nigéria"),
            "day": datetime.strptime("25/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Beira Rio"),
            "type": 1,
            "group": "f",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Bósnia"),
            "visited": Team.objects.get(name_pt__icontains="Irã"),
            "day": datetime.strptime("25/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Fonte Nova"),
            "type": 1,
            "group": "f",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Gana"),
            "visited": Team.objects.get(name_pt__exact="EUA"),
            "day": datetime.strptime("16/06/2014 19:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena das Dunas"),
            "type": 1,
            "group": "g",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Alemanha"),
            "visited": Team.objects.get(name_pt__icontains="Portugal"),
            "day": datetime.strptime("16/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Fonte Nova"),
            "type": 1,
            "group": "g",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Alemanha"),
            "visited": Team.objects.get(name_pt__icontains="Gana"),
            "day": datetime.strptime("21/06/2014 16:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Castelão"),
            "type": 1,
            "group": "g",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Portugal"),
            "visited": Team.objects.get(name_pt__exact="EUA"),
            "day": datetime.strptime("22/06/2014 18:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Amazônia"),
            "type": 1,
            "group": "g",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Portugal"),
            "visited": Team.objects.get(name_pt__icontains="Gana"),
            "day": datetime.strptime("26/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Nacional de Brasília"),
            "type": 1,
            "group": "g",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Alemanha"),
            "visited": Team.objects.get(name_pt__exact="EUA"),
            "day": datetime.strptime("26/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Pernambuco"),
            "type": 1,
            "group": "g",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Bélgica"),
            "visited": Team.objects.get(name_pt__icontains="Argélia"),
            "day": datetime.strptime("17/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Mineirão"),
            "type": 1,
            "group": "h",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Rússia"),
            "visited": Team.objects.get(name_pt__icontains="Coréia do Sul"),
            "day": datetime.strptime("17/06/2014 18:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena Pantanal"),
            "type": 1,
            "group": "h",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Argélia"),
            "visited": Team.objects.get(name_pt__icontains="Coréia do Sul"),
            "day": datetime.strptime("22/06/2014 16:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Beira Rio"),
            "type": 1,
            "group": "h",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Bélgica"),
            "visited": Team.objects.get(name_pt__icontains="Rússia"),
            "day": datetime.strptime("22/06/2014 13:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Maracanã"),
            "type": 1,
            "group": "h",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Bélgica"),
            "visited": Team.objects.get(name_pt__icontains="Coréia do Sul"),
            "day": datetime.strptime("26/06/2014 17:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena de São Paulo"),
            "type": 1,
            "group": "h",
        },
        {
            "home": Team.objects.get(name_pt__icontains="Argélia"),
            "visited": Team.objects.get(name_pt__icontains="Rússia"),
            "day": datetime.strptime("26/06/2014 17:00", "%d/%m/%Y %H:%M"),
            "stadium": Stadium.objects.get(name__icontains="Arena da Baixada"),
            "type": 1,
            "group": "h",
        }
    ]

    # CREATE First Round

    def create_first_match():
        dict_not_creted = []
        for m in matches:
            get_matches = Match.objects.filter(
                day_match=m.get('day'),
                type_match=m.get('type'),
                team_home=m.get('home'),
                team_visited=m.get('visited'),
                group=m.get('group'),
                stadium=m.get('stadium'),
            )

            if not get_matches:
                Match.objects.create(
                    day_match=m.get('day'),
                    type_match=m.get('type'),
                    team_home=m.get('home'),
                    team_visited=m.get('visited'),
                    group=m.get('group'),
                    stadium=m.get('stadium'),
                )
            else:
                dict_not_creted.append({
                    'visited': get_matches[0].team_visited,
                    'home': get_matches[0].team_home,
                })

        if dict_not_creted:
            print "Partida já existe e não foi criado: %s" % (dict_not_creted)

    create_first_match()
